name: Deploy Docs
on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    environment: live
    env:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PROD_GCP_SERVICE_ACCOUNT_KEY  }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.PROD_GCP_SERVICE_ACCOUNT }}
      CLUSTER: www-spot
      GCP_PROJECT: print-nanny
      GCP_ZONE: us-central1-c
      USE_GKE_GCLOUD_AUTH_PLUGIN: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Write deploy key
        run: echo $GCP_SERVICE_ACCOUNT_KEY > key.json
      - name: Active Service Account
        run: |
          sudo apt-get install apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
          gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=key.json
          gcloud container clusters get-credentials $CLUSTER --region=$GCP_ZONE --project $GCP_PROJECT
      - name: Configure docker registry credentials
        run: gcloud auth configure-docker
      - name: Build Container Image
        id: ui
        run: |
          make image
      - name: Deploy to live cluster
        id: deploy
        run: |
          make deploy-k8s

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🚀 Deployed {{ EVENT_PAYLOAD.repository.full_name }}@{{ GITHUB_SHA }} 🚀
